version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - '3001:3000'
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - '3000:3000'
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: accounting
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
