github.com:
    users:
        allyelvis:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: allyelvis
