github.com:
    users:
        allyelvis:
            oauth_token: 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
    git_protocol: https
    user: allyelvis
    oauth_token: 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
