github.com:
    users:
        allyelvis:
            oauth_token: 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
    git_protocol: https
    user: allyelvis
    oauth_token: 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
