github.com:
    users:
        allyelvis:
            oauth_token: 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
    git_protocol: https
    user: allyelvis
    oauth_token: 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
